### ISSUE TITLE
The build dependency g++ is missing 

### ISSUE THREAD

**Issue by maxhbr** [amazon-ospo/thunderabsa-cli#5]
The build dependencies are missing `g++`. See:

https://github.com/amazon-ospo/thunderabsa-cli/blob/68b2f5649ebae24ebf36d01251550537284d961d/README.md?plain=1#L16

It is necessary to additionally run `apt-get install g++` so that ` pip3 install thundera-bsa` succeeds.

**Comment by oscarvalenzuelab** [comment]
Hi!

Thanks for the reminder. I add it to the documentation.

Thanks,
Oscar
